In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
device = "cuda"
torch.device(device)

device(type='cuda')

**Introduction to tensors**

Scalar

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
#Get tensor back as python int
scalar.item()

7

Vector

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

Matrix

In [10]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

Tensor

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random Tensors

In [17]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [18]:
random_tensor

tensor([[0.3298, 0.9645, 0.0281, 0.6032],
        [0.2739, 0.8143, 0.5595, 0.8117],
        [0.1582, 0.7446, 0.2162, 0.2506]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
#Create a random tensor of size (2,10,10)
random_tensor1 = torch.rand(2,10,10)

In [22]:
random_tensor1

tensor([[[0.0051, 0.8164, 0.0926, 0.8896, 0.2327, 0.8746, 0.1768, 0.3795,
          0.1615, 0.6444],
         [0.8246, 0.5878, 0.6556, 0.4352, 0.0693, 0.4991, 0.1874, 0.6599,
          0.1971, 0.4158],
         [0.1853, 0.5456, 0.2662, 0.0385, 0.9078, 0.9798, 0.9896, 0.6765,
          0.0422, 0.4372],
         [0.2713, 0.8232, 0.4742, 0.9138, 0.4043, 0.7898, 0.2985, 0.2757,
          0.8847, 0.9845],
         [0.2785, 0.8820, 0.4536, 0.9539, 0.2847, 0.6207, 0.4761, 0.4132,
          0.7632, 0.3728],
         [0.0732, 0.6521, 0.0451, 0.2640, 0.4222, 0.5152, 0.1121, 0.8475,
          0.2458, 0.1630],
         [0.7018, 0.7071, 0.4634, 0.4606, 0.7043, 0.7933, 0.9430, 0.6341,
          0.7945, 0.3938],
         [0.4526, 0.1552, 0.0942, 0.4147, 0.6824, 0.8273, 0.8371, 0.5409,
          0.2779, 0.2179],
         [0.2634, 0.8558, 0.6469, 0.4431, 0.8732, 0.3755, 0.3157, 0.9291,
          0.9403, 0.5518],
         [0.5809, 0.7801, 0.9748, 0.4728, 0.0168, 0.2224, 0.3437, 0.6901,
          0.1415,

In [23]:
random_tensor1.ndim

3

In [24]:
random_tensor1.shape

torch.Size([2, 10, 10])

In [25]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3,224,224) #Colour channels,Height,Width

In [26]:
random_image_size_tensor

tensor([[[0.4637, 0.2538, 0.3616,  ..., 0.1541, 0.9971, 0.6534],
         [0.6946, 0.1725, 0.4881,  ..., 0.2800, 0.6843, 0.0648],
         [0.5010, 0.8042, 0.9746,  ..., 0.1594, 0.8420, 0.5700],
         ...,
         [0.7961, 0.9937, 0.8375,  ..., 0.3589, 0.9434, 0.7956],
         [0.2950, 0.4165, 0.8319,  ..., 0.7222, 0.0326, 0.7150],
         [0.2541, 0.5723, 0.7777,  ..., 0.2951, 0.7500, 0.2379]],

        [[0.9284, 0.6490, 0.4999,  ..., 0.4314, 0.5953, 0.3063],
         [0.8527, 0.3317, 0.3061,  ..., 0.6812, 0.1314, 0.8215],
         [0.1994, 0.0180, 0.9974,  ..., 0.9580, 0.0342, 0.5456],
         ...,
         [0.0481, 0.6419, 0.0974,  ..., 0.6967, 0.8863, 0.5642],
         [0.5814, 0.1573, 0.2287,  ..., 0.2671, 0.2455, 0.9530],
         [0.1594, 0.2297, 0.2019,  ..., 0.3398, 0.2180, 0.2527]],

        [[0.7855, 0.0963, 0.4828,  ..., 0.5111, 0.2275, 0.8008],
         [0.0423, 0.8618, 0.2796,  ..., 0.8527, 0.2204, 0.5373],
         [0.7337, 0.6772, 0.2658,  ..., 0.1058, 0.1664, 0.

In [27]:
random_image_size_tensor.ndim

3

In [28]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

Zeros and Ones

In [29]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

Create a range of tensors

In [32]:
#Use torch.range()
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
torch.arange(2,10)

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
random = torch.arange(start=1, end=10, step=3)
random

tensor([1, 4, 7])

In [36]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Dealing with tensor data types

In [38]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [39]:
float_32_tensor.dtype

torch.float32

In [40]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16_tensor.dtype

torch.float16

In [42]:
int_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.int,
                               device=None,
                               requires_grad=False)
int_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
int_tensor * float_32_tensor #Might not always be possible if tensors of different dtypes

tensor([ 9., 36., 81.])

Getting information from tensors

In [44]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7686, 0.6724, 0.5841, 0.0355],
        [0.8096, 0.0422, 0.1665, 0.1097],
        [0.3759, 0.6305, 0.6748, 0.2317]])

In [45]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7686, 0.6724, 0.5841, 0.0355],
        [0.8096, 0.0422, 0.1665, 0.1097],
        [0.3759, 0.6305, 0.6748, 0.2317]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors (Basics)

In [46]:
#Addition
tensor1 = torch.tensor([1,2,3])
tensor1 + 10

tensor([11, 12, 13])

In [47]:
#Multiplication
tensor1 * 10

tensor([10, 20, 30])

In [48]:
tensor1

tensor([1, 2, 3])

In [49]:
#Substract
tensor1 - 10

tensor([-9, -8, -7])

In [50]:
#Torch inbuilt functions
torch.mul(tensor1, 10)

tensor([10, 20, 30])

In [51]:
torch.add(tensor1, 10)

tensor([11, 12, 13])

Matrix Multiplication

In [52]:
#Element wise multiplication
print(tensor1, "*", tensor1)
print(f"Equals: {tensor1*tensor1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [53]:
torch.matmul(tensor1,tensor1)

tensor(14)

In [54]:
#Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [55]:
%%time
value = 0
for i in range(len(tensor1)):
    value += tensor1[i] * tensor1[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1.76 ms


In [56]:
%%time
torch.matmul(tensor1,tensor1)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [57]:
tensor1 @ tensor1

tensor(14)

In [58]:
%%time
tensor1 @ tensor1

CPU times: total: 0 ns
Wall time: 2.02 ms


tensor(14)

In [59]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.8816, 0.8343],
        [0.6282, 0.6220]])

In [60]:
torch.mm(torch.rand(2,3),torch.rand(3,2)) #Replacement for matmul (the same thing but short)

tensor([[0.3469, 0.5501],
        [0.7177, 0.4338]])

In [61]:
tensor = torch.rand(3,4)

In [62]:
tensor

tensor([[0.1510, 0.6936, 0.0246, 0.2715],
        [0.0343, 0.1821, 0.7592, 0.8865],
        [0.4716, 0.9087, 0.1151, 0.0152]])

In [63]:
tensor.T #Gives transpose ie. (3,4) to (4,3)

tensor([[0.1510, 0.0343, 0.4716],
        [0.6936, 0.1821, 0.9087],
        [0.0246, 0.7592, 0.1151],
        [0.2715, 0.8865, 0.0152]])

Max, Mean & Sum

In [64]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
x.min()

tensor(0)

In [66]:
torch.min(x)

tensor(0)

In [67]:
x.max()

tensor(90)

In [68]:
torch.max(x)

tensor(90)

In [70]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [72]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [73]:
torch.median(x.type(torch.float32))

tensor(40.)

In [74]:
torch.mode(x.type(torch.float32))

torch.return_types.mode(
values=tensor(0.),
indices=tensor(0))

In [75]:
x.sum()

tensor(450)

In [76]:
torch.sum(x)

tensor(450)

Finding the positional min and max tensors

In [77]:
torch.argmax(x.type(torch.float32))

tensor(9)

In [78]:
torch.argmin(x.type(torch.float32))

tensor(0)

In [79]:
x.argmin()

tensor(0)

In [80]:
x.argmax()

tensor(9)

Reshaping,viewing and stacking

In [81]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [82]:
#Reshape (Adding dimension)
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing its view
z = y.view(1, 9) #Changing z changes y
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [86]:
z[:, 0] = 5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [89]:
#Stack tensors on each other
y_stacked = torch.stack([y, y, y, y])
y_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [90]:
y_stacked = torch.stack([y, y, y, y], dim=1)
y_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

Squeeze,Unsqueeze & Permute

In [91]:
y_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
y_reshaped.squeeze().shape

torch.Size([9])

In [94]:
y_reshaped.unsqueeze(dim=2)

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [95]:
y_reshaped.unsqueeze(dim=2).shape

torch.Size([1, 9, 1])

In [96]:
y_reshaped.unsqueeze(dim=1)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [97]:
y_reshaped.unsqueeze(dim=1).shape

torch.Size([1, 1, 9])

In [101]:
y_reshaped.squeeze().unsqueeze(dim=0).shape

torch.Size([1, 9])

In [ ]:
t = torch.rand(224,224,3)
s = t.permute(2,0,1) #Shifts axis 0->1, 1->2, 2->3
print(f"Old shape {t.shape} & New shape {s.shape}")

Old shape torch.Size([224, 224, 3]) & New shape torch.Size([3, 224, 224])


In [107]:
t[0,0,0] = 0.68

In [108]:
t

tensor([[[0.6800, 0.6652, 0.9249],
         [0.2054, 0.6734, 0.6304],
         [0.9810, 0.3596, 0.3845],
         ...,
         [0.4552, 0.3659, 0.5693],
         [0.0954, 0.8672, 0.1184],
         [0.0548, 0.6919, 0.5126]],

        [[0.7103, 0.9099, 0.5655],
         [0.9286, 0.3393, 0.6498],
         [0.5957, 0.7069, 0.6106],
         ...,
         [0.6961, 0.3421, 0.1338],
         [0.0208, 0.5012, 0.0319],
         [0.7454, 0.3002, 0.1495]],

        [[0.8544, 0.1387, 0.0742],
         [0.9296, 0.9875, 0.5622],
         [0.5290, 0.6471, 0.6356],
         ...,
         [0.3697, 0.2170, 0.3669],
         [0.4989, 0.7095, 0.0591],
         [0.7841, 0.3522, 0.6009]],

        ...,

        [[0.8922, 0.4211, 0.1305],
         [0.6730, 0.8749, 0.2159],
         [0.3846, 0.9585, 0.6940],
         ...,
         [0.3188, 0.2749, 0.0937],
         [0.8340, 0.2208, 0.7305],
         [0.3309, 0.9860, 0.5878]],

        [[0.6402, 0.7326, 0.8829],
         [0.1844, 0.5900, 0.1701],
         [0.

Indexing

In [109]:
a = torch.arange(1, 10).reshape(1,3,3)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [110]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [111]:
a[0][0]

tensor([1, 2, 3])

In [112]:
a[0,0]

tensor([1, 2, 3])

In [113]:
a[0,0,0]

tensor(1)

In [115]:
a[0,0,1]

tensor(2)

In [117]:
a[1,1,1] #Because we only got 1 dimension there 

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [118]:
a[0,2,2]

tensor(9)

In [119]:
#You can also use ":" to select "all" of a target dimension
a[:, 0]

tensor([[1, 2, 3]])

In [121]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
a[:,:,1]

tensor([[2, 5, 8]])

In [123]:
#Get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
a[:,1,1]

tensor([5])

In [124]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
a[0,0,:]

tensor([1, 2, 3])

In [130]:
a[:,:,2]

tensor([[3, 6, 9]])