**PyTorch and NumPy**

In [1]:
import torch
import numpy as np

In [12]:
#NumPy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [13]:
tensor1 = torch.from_numpy(array).type(torch.float32) #To make dtype as we want
tensor1.dtype

torch.float32

In [14]:
#Change the value of array, what will this do to 'tensor'?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [23]:
#Tensor to NumPy array
tensor2 = torch.ones(7)
numpy_tensor = tensor2.numpy()
tensor2, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [24]:
numpy_tensor.dtype

dtype('float32')

In [25]:
#Change the tensor, what will happen to 'numpy_tensor'?
tensor2 = tensor2 + 1
tensor2, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducbility

In [34]:
#Doesnt give same output always
torch.rand(3,3)

tensor([[0.3821, 0.6605, 0.8536],
        [0.5932, 0.6367, 0.9826],
        [0.2745, 0.6584, 0.2775]])

In [35]:
torch.rand(3,3)

tensor([[0.8573, 0.8993, 0.0390],
        [0.9268, 0.7388, 0.7179],
        [0.7058, 0.9156, 0.4340]])

In [36]:
#Using a seed to flavour the randomness ie. it will always get the same input for rand
torch.manual_seed(123)
torch.rand(3,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])

In [37]:
torch.manual_seed(123)
torch.rand(3,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])

In [40]:
#Doesnt work the same in this case due to both rand following each other
torch.manual_seed(234)
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)
tensor_A,tensor_B

(tensor([[0.9276, 0.5817, 0.0962],
         [0.0014, 0.5745, 0.7127]]),
 tensor([[0.3646, 0.0531, 0.1347],
         [0.9168, 0.8947, 0.1901]]))

In [41]:
torch.manual_seed(234)
tensor_C = torch.rand(2,3)

In [42]:
torch.manual_seed(234)
tensor_D = torch.rand(2,3)

In [44]:
#Works in this scenario
tensor_C == tensor_D

tensor([[True, True, True],
        [True, True, True]])

In [47]:
#This also works
torch.manual_seed(123)
tensor_E = torch.rand(2,3)
torch.manual_seed(123)
tensor_F = torch.rand(2,3)
tensor_E == tensor_F

tensor([[True, True, True],
        [True, True, True]])

Different ways to access a GPU:

1.Google Colab

2.GPU of own

3.Use cloud computing

In [49]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [50]:
device

device(type='cuda')

In [53]:
torch.cuda.is_available()

True